return {
   {
      "nvim-treesitter/nvim-treesitter",
      build = ":TSUpdate",
      opts = {
         sync_install = false,
         auto_install = true,
         highlight = { enable = true },
         indent = { enable = true },
         ensure_installed = {
            "bash",
            "c",
            "cpp",
            "css",
            "csv",
            "diff",
            "dockerfile",
            "go",
            "gomod",
            "gosum",
            "html",
            "javascript",
            "jq",
            "jsdoc",
            "json",
            "jsonc",
            "lua",
            "luadoc",
            "luap",
            "make",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "regex",
            "rst",
            "ruby",
            "rust",
            "sql",
            "terraform",
            "toml",
            "vim",
            "vimdoc",
            "yaml",
         }
      }
   }
}
