# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="kolo"

# Load plugins
plugins=(git)

# Load oh-my-zsh initialization script
source $ZSH/oh-my-zsh.sh
